### ISSUE TITLE
Set up train schedules based on diagrams.

### ISSUE THREAD

**Issue by kaminogi** [klyte45/TransportLinesManager#103]
I'd like to schedule trains to depart from the depot or station and return to the depot again via various stations.
This scheduling allows for flexible and realistic train operations such as waiting for trains to pass or overtake.

**Comment by kaminogi** [comment]
In Japan, there is a famous city development game base on transport networks named "A-Train".
This video is the scheduling feature for trains.
When the train goes on "Wizard Mode" and the train approaching the station, the settings window will open and we can manage pass or stop and time etc. 
non-time based scheduling is also available like "one train arrived at the next platform, wait for 5 mins then depart".

I'm not sure think this is the best solution for TLM, but I hope this would be helpful for considering the feature.
https://www.youtube.com/watch?v=OsyKvAucFFk

**Comment by Kamine9856** [comment]
I am Japanese.
Before this concept started, I continued to develop it to make a timetable mod.
However, there was a limit to my technology, so I am currently working with other people through trial and error.
I am very interested in this concept.
If realized, I think we can make the game even more enjoyable.
I think there is also demand.

**Comment by klyte45** [comment]
I guess it can be released as a "TLM plugin", like other mods that works well with TLM as dependency. Probably it will require Real Time as well, so this would be the reason to be released separated from the main mod.

Question: Is the Cities In Motion 2 game engine a good example to follow? Or transport fever?

**Comment by comahoney21** [comment]
> I guess it can be released as a "TLM plugin", like other mods that works well with TLM as dependency. Probably it will require Real Time as well, so this would be the reason to be released separated from the main mod.
> 
> Question: Is the Cities In Motion 2 game engine a good example to follow? Or transport fever?

I personally really liked the "bus scheduling" timetables in Cities in Motion 2!

**Comment by klyte45** [comment]
As said here in June 2, this won't be implemented in TLM itself. Anyway, it will be noted for future reference, in case of the mod plugin get to be developed.

It would get easier with the Terminal Stop feature added at v14, but also it would require a change in the game vehicle spawning way of work, since it wouldn't be by budget anymore, instead would be by vehicle or by schedule demand. The implementation idea itself isn't being abandoned, but it would make TLM even more complex than it is already.

That said, I will close this issue, but may get back in this subject in another mod project.
