### ISSUE TITLE
Issues drawing map

### ISSUE THREAD

**Issue by gitblogger** [klyte45/TransportLinesManager#108]
For some reason, the "Draw city map" feature draws a blank map of my city.

**Comment by klyte45** [comment]
Need more info:

- Which kind of public transport do you have in your city?
- Blank you say is completly void file or just a map with no line listed?

**Comment by gitblogger** [comment]
I have all types of public transport. There are no lines listed on the map.

**Comment by klyte45** [comment]
I will need your output_log.txt file. Try to export the map then follow instruction in the Report-a-bug helper button to get the file and send it here:
![image](https://user-images.githubusercontent.com/11671356/135974853-e89f727a-4fdc-4de4-9057-20a2c0a9ea73.png)

**Comment by gitblogger** [comment]
[Uploading Singapore_f4fd12b3-31c8-4eca-953f-0381e1d39c91.zip…](
[Uploading output_log.txt…]()
)
Here it is. i have also attached my generated map.

**Comment by gitblogger** [comment]
Here it is. I have also attached my generated map.
[Singapore_f4fd12b3-31c8-4eca-953f-0381e1d39c91.zip](https://github.com/klyte45/TransportLinesManager/files/7284206/Singapore_f4fd12b3-31c8-4eca-953f-0381e1d39c91.zip)
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7284214/output_log.txt)

**Comment by klyte45** [comment]
It opened here: 
![image](https://user-images.githubusercontent.com/11671356/136637988-9afd87f0-402b-4e04-9ef1-733f874fec8a.png)
But it took a long long time... This is because the map is huge so there are a lot of stuff to load. Here was about 2min, there can be less or more time depending on your processing power.

Btw, nice city 😁

Closing the issue
