### ISSUE TITLE
Addition of spawn timings, bus distancing, and specific fleet selection

### ISSUE THREAD

**Issue by A121314151** [klyte45/TransportLinesManager#118]
Hello there,
Proud user of TLM on my friend's copy of the game. However, could we have the addition of spawn timings like IPT2, change the distance between buses to make frequency more realistic, and also specifically choose our buses for each route, such as choosing one special bus within multiple bus models, similar to selecting buses in IPT2, unless service vehicle selector works for this?
Thanks!

**Comment by isaac-prog** [comment]
+1

If this mod contains all of ipt2 features it would certainly be great

**Comment by klyte45** [comment]
Spawn times was already discussed in TLM before but was decided to not do it because it will require too much work. The unbunching is done already while the line is running, in the last/terminal stops (if bus/tram/trolleybus express lines are turned on) or in the next stop (in any other modals/when express lines are disabled).

The model selection exclusive for line already exists in TLM, but imply on all other settings to be also specific about it too (budget, ticket price, etc). Take a look at model select screen. A model count by line feature have no priority to be implemented here.

Closing this, but feel free to question if need more information.
