### ISSUE TITLE
Mod requires KlyteAddresses???

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#162]
Recently I am debugging my CSL environment, and have discovered that this mod is requiring an assembly called KlyteAddresses. Is this something that should be dealt with? I simply do now know what this KlyteAddresses is and this assembly seems important.

**Comment by klyte45** [comment]
No, actually it's not required. The mod checks if Addresses is available to enhance the experience, but it will use the Fallback class if the other mod is not found. [Check the files at ModShared folder to see implementation details.](https://github.com/klyte45/TransportLinesManager/tree/a3aa4dea09ba2a7b564a5b698539611d25022641/ModShared) 

The implementation choose is done [at the Controller initialization when loading a city](https://github.com/klyte45/TransportLinesManager/blob/a3aa4dea09ba2a7b564a5b698539611d25022641/TLMController.cs#L170), that when it checks if the Addresses mod is available. [Look at PluginUtils method to see details of this check](https://github.com/klyte45/KlyteCommonsIncludable/blob/84147187f2cd2e9d9aee284f705a0d5c49f43701/Utils/PluginUtils.cs#L24)

Note the difference between regular and fallback bridge classes is that the regular one requires the Addresses mod as an extern alias to access their types, while the fallback try to resolve the methods with information available in TLM, with no connection to other mod.

**Comment by klyte45** [comment]
Okay, there's a problem with the current implementation of the plugin utils feature. It crashes the game since the main bridge type cannot be loaded.

However, I fixed it by passing the main class (the one that have dependency with another mod) via string, then loading the type only after ensuring the required dll exists in the environment:  https://github.com/klyte45/KlyteCommonsIncludable/blob/07ee1a2d44f7a4be8f2b07037785e85f44f3f5c1/Utils/PluginUtils.cs#L28

This fix will be available in TLM in seconds, and for WTS and Addresses will be added later.
