### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by JumpJumpo** [klyte45/TransportLinesManager#171]
First of all: WOW! Your mods are definitively my favs in the games! :D

I want to inform you that with the new update there is some incompatibility with these mods (I was using that also before the last update):
- Advanced stop selection (ex MTSE)
- More networks stuff
- Spawn points fix
- Intercity bus controll

When I try lo load my old game CS crasches.

**Comment by klyte45** [comment]
To the points:
- Advanced stop selection is fine here. Which issue you are having with it?
- More network stuff is broken since a while (it hides the sunset harbor stuff, as example)
- Haven't tried the SPF, but it shouldn't be affected
- I believe IBC will really be incompatible by now because the same feature is under implementation - the first release allowed this job just for train stations now and the buses implementation will be added in a future release. This will be a trade off by now.
