### ISSUE TITLE
Regional Platform Window

### ISSUE THREAD

**Issue by EpiccraftTV** [klyte45/TransportLinesManager#178]
Is it possible to make the TLM Regional Platform window moveable? I use Service Vehicle Selector 2 which has the window right next to the main building window and thus prevents me from being able to use the regional platform window.

**Comment by klyte45** [comment]
Well, firstly isn't recommended to use SVS along TLM, since they changes common code. I advise you to migrate to [Vehicle Master Control](https://steamcommunity.com/sharedfiles/filedetails/?id=2299901014)

About make the window moveable, it's a problem too big to be handled ATM because it lays on the lack of a good UI structure in the base game, so it wouldn't be considered to be implemented.
