### ISSUE TITLE
Express bus/tram/trolleybuses

### ISSUE THREAD

**Issue by EpiccraftTV** [klyte45/TransportLinesManager#179]
Having the ability to run certain bus/trolleybus/tram routes as "express" routes would be very useful, especially for some of  the lower demand routes that don't have to worry to much about vehicle spacing as a higher demand/higher vehicle count route.

**Comment by klyte45** [comment]
Well, express buses/trams/trolleybuses are activated by default since TLM 14, but no plans to make it a per-line setting.
Otherwise, you can separate the lines in different prefixes groups to handle models and budgets exclusive for them all, or set the line specific budget using the option in line detail screen
