### ISSUE TITLE
Can you please release this mod on cities-mods.com

### ISSUE THREAD

**Issue by bolandnick18** [klyte45/TransportLinesManager#180]
Can you please release this mod on https://cities-mods.com/xlex/categories/cities-skyline.53/ so others users can enjoy it as well

**Comment by klyte45** [comment]
Sorry but I have no time for this. 
But, a working version is always available here in the GitHub at [_requiredDLLs](https://github.com/klyte45/TransportLinesManager/tree/master/_requiredDLLs) folder.
Feel free to get it there anytime, but I suggest to make a link to this repository instead of replicate the file, since it's always updated.

**Comment by bolandnick18** [comment]
Ok if you do have time you are more welcome to register a account and publish it there
