### ISSUE TITLE
Incorrect Destinations

### ISSUE THREAD

**Issue by UpLift-Vancouver** [klyte45/TransportLinesManager#182]
Transit vehicles which have Write the Signs in use in conjunction with TLM are not showing the correct destinations.

https://steamcommunity.com/sharedfiles/filedetails/?id=2702853987
The screenshot linked above shows an example of this problem: the tram is supposed to show Flanders & Thompson as its destination, but it is instead showing Large Playground (a point of interest that is nowhere near either of the terminus stops) on its sign.

A suggestion to fix this would be to designate stops as terminus or major stops that are only allowed to show on signs set to Current Destination mode while other stops would not be allowed to appear on signs set in Current Destination mode.

**Comment by klyte45** [comment]
Well, actually you can do it by right-clicking in the terminus stations. It will force them to be the line destinations (so you will need to make one of them to be the first stop, and set the other as terminus and the magic is done). 
Also, manually typing the name of station (instead of letting it be given by autonaming the station) will increase relevance when getting the half-trip destinations.

If this doesn't work, reopen this.
