### ISSUE TITLE
I would like to set vehicles on a per-line basis, not per prefix

### ISSUE THREAD

**Issue by jotakob** [klyte45/TransportLinesManager#208]
I noticed that whenever I set the vehicle for a line, it automatically applies that setting to the whole "Prefix": I'm guessing line prefixes are used as group of some sort? Not sure though since I couldn't find any documentation.
However, I often want to set the vehicles on a per-line basis, but I don't want the lines to each have a prefix, since that would mess up the numbers. I expected that "Unprefixed" lines act as if they have no prefix, and I can set the vehicle on a per-line basis. However, it seems that "Unprefixed" is simply another group that shares vehicle settings.

I'd expect that different "Unprefixed" lines can have different vehicle setups.

**Comment by MatthewForrester** [comment]
Have you tried activating the "specific line config" radio button?

In 1.13.x, this allowed us to choose a different vehicle for each line.

Unfortunately in 1.14, it does not seem to work, perhaps because of [this bug](https://forum.paradoxplaza.com/forum/threads/cities-skylines-steam-cant-select-a-specific-bus-for-my-bus-lines.1508054/#post-28038645) in vanilla.

**Comment by jotakob** [comment]
Oh yeah that does work, thanks! I didn't understand what that button was doing before.
