### ISSUE TITLE
Bus Lines in Menu not organized by Number/Code/Name

### ISSUE THREAD

**Issue by CanadianMarc** [klyte45/TransportLinesManager#218]
![image](https://user-images.githubusercontent.com/24379820/153737978-b7f32432-a922-478c-82fa-450fd06f21a7.png)
![image](https://user-images.githubusercontent.com/24379820/153737977-fa7f76a6-7aa9-4e03-93b1-7c3f04092544.png)

I believe it's a simple issue, the numbers should be from least to greatest or vice versa when color/code or line name is clicked, however it is sorting all the codes with 0 as the start first, then all the 1s, then 2s, etc.
Lets say I have the following list of routes:
ROUTES: [1, 2, 6, 8, 11, 21, 34, 35, 39, 47, 77, 105, 205]

Expected Display:
[1, 2, 6, 8, 11, 21, 34, 35, 39, 47, 77, 105, 205]

Actual Display:
[1, 11, 105, 2, 21, 205, 34, 35, 39, 47, 77]

I do not know when this bug started, however I do remember when it used to organize the routes properly by code/name.

**Comment by klyte45** [comment]
Well this is tricky, but the displayed list is correct 😅

I suppose you are sorting by Line Name, which doesn't compute number as numbers, but as a string. So, 1 is before 10 that's before 2 (because they are compared digit by digit, not as a absolute value)

Sorting by color/code column may order they in correct order.

**Comment by CanadianMarc** [comment]
Still has the same issue regardless of which one I sort it as.
