### ISSUE TITLE
[BUG] Cannot explicitly set ticket price to 0

### ISSUE THREAD

**Issue by Vectorial1024** [klyte45/TransportLinesManager#237]
**Describe the bug**
At some point I decided to try making a $0 ticket price bus line, but discovered that when setting the ticket price to 0, it ueses the default ticket price (100) instead.

**To Reproduce**
(Trivial enough.)

**Additional context**
I thought about just adding a new district and enable "Free Public Transport" option, but then it seems tedious and may overlap with existing districts.

By the way, would the ticket price config from this mod override policies such as "Free Public Transport" (x0) or "High Ticket Prices" (x1.25)?

**Comment by klyte45** [comment]
Well, it's a delicate issue once it lays on overuse of 0 value. The 0 means "default" since ever in TLM, and this is the common behavior. To make a ticket-free line, it would require a new feature instead.

Also, the modifier aren't changed in TLM, once they are per-district and not per-line. So a line which covers a district with free ticket police and another without that policy will earn fares in the last one, but not in the first.
