### ISSUE TITLE
Problem with regional trains still enabled even though the station intercity trains radio button is off.

### ISSUE THREAD

**Issue by citymangler** [klyte45/TransportLinesManager#275]
Hi,

This is a really good mod, unfortunatly I have a couple of problems.

### Intro

This could be due to the ongoing general bug relating to the 'Allow intercity trains' radio button on stations not working correctly. To recap the birthday update broke this functionallity and the radio button cannot be selected in the vanila game. There is a work around 'Allow intercity trains' (currently v1.2) by sleepy which re- enables the button and once again allows you to disable vanilla intercity (regional) trains. I have this mod enabled so there could be an odd interaction between it and TLM.

### Issue

1. If you have a station with multiple platforms and are using the 'Allow intercity trains V1.2' fix for the above issue then TLM still appears to allow regional trains even when the radio button for intercity trains is off.  Please see the 1st screen shot on https://imgur.com/a/b5Ayvyd .

Oddly TLM does remove some of the regional connections when you disable allow intercity train radio, just not all of them.

2. If you turn on TLMs own 'Use TLM regional platform' settings then there are no regional connections shown - so I am assuming that all regional trains are then disabled. However the base game window's close button is now obscured by TLM's windows, meaning you cannot close it - see second picture at https://imgur.com/a/b5Ayvyd .

You can close the window by pressing escape, however could the TLM windows be lowered or moved to the right?

**Comment by klyte45** [comment]
1) The TLM list ANY regional lines, it being managed by the mod itself or not. It's based in the vanilla setting and if there's another mod overriding it, will have conflict. 
2) Same as above. The lines shown in the Regional Lines section are effectivelly actives in the game, since it count nodes from the station to get these lines information.

As well, some other mods that doesn't care so much about nodes linked listing may break this behavior, as the old versions of Touch This! Tool as example

The window overlap is an issue related to the bugged UI from vanilla, and it can work or not as designed depending on PC settings. A new IPT + TLM mod is coming soon to solve this kind of issue.
