### ISSUE TITLE
Opening line creation tool automatically opens another line line stop overlay

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#41]
Every time I open line creation tool in (the stop icon in the build menu), it automatically displays me this:
![image](https://user-images.githubusercontent.com/4341091/86362155-849c6f80-bc7d-11ea-9b09-3eb60b2bee37.png)
and in most cases it overlaps my build menu buttons. It stays there until I close the build tool or place a stop anywhere on the map.

Version 13.5 (happened in 13.4 also)

**Comment by klyte45** [comment]
You can disable this panel by clicking in the button on top of the public transport window, you can disable the map if it is causing any issue. This is the option:
![image](https://user-images.githubusercontent.com/11671356/110968326-23fa2200-8336-11eb-916d-918bddd2d286.png)
Closing issue since it's already supported in the mod

**Comment by GameBurrow** [comment]
Thanks, didn't even think about that.
