### ISSUE TITLE
Use Real Time mod time instead of day/night clock if day/night cycle is disabled

### ISSUE THREAD

**Issue by Ibigoo** [klyte45/TransportLinesManager#48]
Hi! I just noticed the vehicle count on every line remain the same regardless the starting hour. For details please check the attached screenshot. Please let me know if you need more information. Thank you.
![tml](https://user-images.githubusercontent.com/80781912/111356949-24255500-8689-11eb-9b72-6e256decfbd2.png)

**Comment by klyte45** [comment]
Weirdly, seems the game is set to 12h (look the TLM clock, that's the reference clock for budget), typically this happens when the day/night cycle is disabled. Is this the case in your game?

The time from TLM comes from game's clock, not from the RealTime. Generally they are the same, and I thought it wouldn't be allowed. I will check the possibility to allow disabled day/night cycle savegames to set the line budget properly

**Comment by Ibigoo** [comment]
Yepp, that was the secret. With enabled day/night cycle the vehicle count is fine.
Thanks if you look into it.

**Comment by klyte45** [comment]
Changed to future due this will be actually a new feature, not exactly a bugfix once the feature is working as designed.

Will be added an option to select the source from the time: if from day/night cycle (like it's now) or from calendar time. 
The first will work for every scenario, except when disabling day/night cycle. The another shall be used if the day/night cycle is off and real time is on. If both are off, there's no way the dynamic budget work, since the game regular time passing is too fast. 

The manual selection will be preferred over an automatic detection because of there are other mods that change the game's time speed making clock run slower, not exclusively the Rush Hour, and detect all them could be too greedy for the target result.

This new feature shall be a global setting, saved globally and shared between saves.

**Comment by Ibigoo** [comment]
Sounds definitely good. Thank you.
Dunno how it is work on GitHub, but from my side you can close this post.

**Comment by klyte45** [comment]
I guess I will close only after the implementation - just for I know what I have in to-do list

**Comment by klyte45** [comment]
The option was added. It only will be read if the day/night cycle is disabled.
Currently at alpha branch
![image](https://user-images.githubusercontent.com/11671356/115980173-d857ac80-a560-11eb-84e6-b966a9f01158.png)
