### ISSUE TITLE
TLM, strange destinations

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#55]
I have one strange bus line, line 3:

![dp7AzExfmB](https://user-images.githubusercontent.com/4341091/114281641-2be9d680-9a48-11eb-9c18-679c002ae309.gif)

![2NzWdWDZMj](https://user-images.githubusercontent.com/4341091/114281924-d3b3d400-9a49-11eb-9896-8d23827f8917.jpg)

Strangely it doesn't choose destinations: Hamilton Bus Station and Belmont Bus Station, which should be the turnaround points. Instead it chooses for destinations: Hamilton Ferry and Hamilton Stn, which are stops randomly in the middle of route.

I have one tram line also, were it similarly doesn't choose the first stop and a stop that is oppsite side of the line as destination, it chooses something in the middle.

I imagine detecting something like this is quite hard, maybe it would be possible to adjust TLM to add End stop (or turnaround stop) selection next to Starts at and this mod would use those stations as destinations?

**Comment by klyte45** [comment]
This happens because of the weight system done for the stop mapping the non-platform dependent transport lines (like buses). It will give more weight to more relevant/greater capacity transport types buildings (like Ferry or Train stations)
The solution for now is to disable station naming rules to use train stations and ferries buildings, but it would be global - or type the name of the line directly. Write the Signs might accept the names - not well tested yet.

The code of this feature is quite old, from before the game first urban bus terminal (came only in Mass Transit). I might review it to always prefer start/end lines in stops that are placed near or inside terminus of the same public transport type (bus terminus for bus lines as example). 

So, also, transferring this issue to TLM project because WTS consumes this information from there.

**Comment by GameBurrow** [comment]
> The solution for now is to disable station naming rules to use train stations and ferries buildings, but it would be global

Tried disabling all naming conventions except disctricts (and it's custom types). No changes. It seems WTS uses the same stations  as destination stops that TLM uses for auto line renaming and it seems TLM ignores thes Starts at value completely in this regards.

> - or type the name of the line directly. Write the Signs might accept the names - not well tested yet.
What exactly did you mean with that? I need to rename the line manually on line menu? If yes then WTS ignores that if I use the destination option.

**Comment by klyte45** [comment]
It must be solved at #59, once the selected stops as terminus will have a heavier weight on line destinations map, also allowing more than 2 destinations in a single line to be used at Write the Signs
