### ISSUE TITLE
Add line identifier string without prefix/sufix option

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/TransportLinesManager#56]
Would it be possible to add line identifier string without prefix/suffix option? I my game I use prefixes to set vehicle groups, nothing else. It would be awesome if I could remove prefix values from the line identifier strings also.

For example I would like to have the option to have this bus to display 3 Hamilton Stn instead of 3B:
![image](https://user-images.githubusercontent.com/4341091/114264555-41cdac00-99f4-11eb-9214-36e6634cfbf2.png)

**Comment by klyte45** [comment]
Was added to latest alpha version a feature allowing to set a custom code to the line. It must solve your problem once you can put anything what you want there. Affects everywhere which uses the string code. 
Examples with Write the Signs:

1. Using default line code generator: 
![image](https://user-images.githubusercontent.com/11671356/115974921-b2b5ad80-a536-11eb-8bfc-721f2ee54cd4.png)

2. Using a custom line code:
![image](https://user-images.githubusercontent.com/11671356/115974929-cd882200-a536-11eb-9bab-c5dd53d13294.png)

WTS have some issues with characters without a full height - it wasn't a problem before because special characters would never appear alone there. I'm looking at it now, but the TLM part is done.
![image](https://user-images.githubusercontent.com/11671356/115974943-ec86b400-a536-11eb-96bf-ce08de8efe80.png)

**Comment by klyte45** [comment]
The misaligning issue was solved in version 0.3 r4 of Write the Signs. This feature is now full testable.
